### ISSUE TITLE
ImportError: cannot import name 'HIBP'

### ISSUE THREAD

**Issue by talperetz** [pegasos1/haveibeenpwned#6]
Python 3.6.2 |Continuum Analytics

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "!@$#!@$%$#/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "!@$@#%@$!@#/python3.6/site-packages/hibp/__init__.py", line 1, in <module>
    from hibp import HIBP, AsyncHIBP
ImportError: cannot import name 'HIBP'

**Comment by GitStoph** [comment]
Also seeing this.

**Comment by rohithvishaal** [comment]
any progress?

**Comment by simplylu** [comment]
Fails due to circular import on *Python 3.10.2 on Linux 5.10.105-1-MANJARO*
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import hibp
  File "/home/user/.local/lib/python3.10/site-packages/hibp/__init__.py", line 1, in <module>
    from hibp import HIBP, AsyncHIBP
ImportError: cannot import name 'HIBP' from partially initialized module 'hibp' (most likely due to a circular import) (/home/user/.local/lib/python3.10/site-packages/hibp/__init__.py)
```
